# place as weatherstation in /etc/logrotate.d
/home/pi/weather-station/logs/forecast.log {
  rotate 4
  weekly
  compress
  missingok
}
/home/pi/weather-station/logs/weather-station.log {
  rotate 4
  weekly
  compress
  missingok
}
